import test from 'node:test';
import assert from 'node:assert/strict';
import { WebhookIngestConnector, validatePublicUrl, GenericRESTReadConnector, GitHubConnector, NotionMirrorConnector, CSVImportExportConnector, LocalSwarmRuntimeAdapter, redactSecrets } from '../dist/packages/connectors/src/index.js';
import { sha256 } from '../dist/packages/core/src/hash.js';
import { PolicyEngine } from '../dist/packages/policy/src/policy.js';

test('webhook authentication schema replay material', async()=>{ const c=new WebhookIngestConnector('secret',1024); const raw=JSON.stringify({type:'lead',idempotencyKey:'abc',payload:{id:'1'}}); const sig=await sha256(`secret:${raw}`); const e=await c.parse(raw,sig,'2026-08-19T00:00:00.000Z'); assert.equal(e.idempotencyKey,'abc'); await assert.rejects(()=>c.parse(raw,'bad'),/AUTH_FAILED/); const bad=JSON.stringify({type:'x'}); const badsig=await sha256(`secret:${bad}`); await assert.rejects(()=>c.parse(bad,badsig),/SCHEMA_INVALID/); assert.throws(()=>new WebhookIngestConnector(''),/REQUIRED/); const huge='x'.repeat(2000); await assert.rejects(()=>c.parse(huge,'x'),/BODY_TOO_LARGE/); });
test('generic REST SSRF guard rejects unsafe targets',()=>{ assert.equal(validatePublicUrl('https://api.github.com/repos/x/y',['api.github.com']).hostname,'api.github.com'); for(const u of ['http://api.github.com/x','https://localhost/x','https://127.0.0.1/x','https://10.0.0.1/x','https://192.168.1.1/x','https://169.254.1.1/x','https://evil.example/x','https://u:p@api.github.com/x']) assert.throws(()=>validatePublicUrl(u,['api.github.com']),/SSRF/); });
test('generic REST handles success, etag, cursor, 304, 429 retry',async()=>{ let calls=0; const fetcher=async()=>{calls++; if(calls===1)return new Response('busy',{status:429,headers:{'retry-after':'1'}}); return new Response(JSON.stringify({ok:1}),{status:200,headers:{etag:'e','x-next-cursor':'c','content-type':'application/json'}})}; const rest=new GenericRESTReadConnector(['example.com'],fetcher); const r=await rest.get('https://example.com/data',{maxRetries:1}); assert.equal(r.ok,true); assert.equal(r.etag,'e'); assert.equal(r.cursor,'c'); const rest304=new GenericRESTReadConnector(['example.com'],async()=>new Response(null,{status:304})); const a=await rest304.get('https://example.com/data',{etag:'e'}); assert.equal(a.etag,'e'); const restFail=new GenericRESTReadConnector(['example.com'],async()=>new Response('x',{status:500})); const f=await restFail.get('https://example.com/data',{maxRetries:0}); assert.equal(f.ok,false); });
test('github connector is read scoped and write capability remains declarative',async()=>{const rest={get:async()=>({ok:true,data:{name:'x'}})}; const g=new GitHubConnector(rest,new PolicyEngine()); const r=await g.readRepo('a','b'); assert.equal(r.ok,true); const planned=g.writeCapability('DEV'); assert.equal(planned.status,'APPROVED'); assert.equal(planned.payload.scope,'isolated-branch');});
test('notion mirror is a pure planner with throttle and cursor semantics',()=>{const n=new NotionMirrorConnector(500); assert.equal(n.throttleMs(1000,1200),300); const plan=n.planUpsert('page-1',{title:'x'},'cursor1'); assert.equal(plan.connector,'notion'); assert.equal(plan.operation,'upsert-page'); assert.equal(n.checkpoint(),'cursor1'); assert.throws(()=>n.planUpsert('bad/id',{},'c'),/INVALID/);});
test('CSV import/export is deterministic',()=>{const c=new CSVImportExportConnector(); const rows=[{name:'A, B',note:'he said "yo"'},{name:'C',note:'ok'}]; const csv=c.stringify(rows); const parsed=c.parse(csv); assert.equal(parsed[0].name,'A, B'); assert.equal(parsed[0].note,'he said "yo"'); assert.equal(c.stringify([]),'');});
test('swarm adapter preserves envelope and denies money authority',async()=>{const s=new LocalSwarmRuntimeAdapter(); const r=await s.dispatch({taskId:'t',authority:['INTERNAL_WRITE'],evidenceRefs:['e'],budget:{ai:1},payload:{kind:'complex'}}); assert.equal(r.taskId,'t'); await assert.rejects(()=>s.dispatch({taskId:'x',authority:['MONEY_MUTATION'],evidenceRefs:[],budget:{},payload:{}}),/DENIED/);});
test('secret redaction covers nested auth token cookie and bearer',()=>{const red=redactSecrets({authorization:'Bearer abc',nested:{apiToken:'secret',cookie:'x',text:'Bearer qwerty'}}); assert.equal(red.authorization,'[REDACTED]'); assert.equal(red.nested.apiToken,'[REDACTED]'); assert.equal(red.nested.cookie,'[REDACTED]'); assert.match(red.nested.text,/REDACTED/);});
